### ISSUE TITLE
Bugsack Errors

### ISSUE THREAD

**Issue by Pernvandamme** [ynazar1/Arh#11]
I'm getting the following error with the mod: 

6x RWN_ArchDistance/DistanceIndicator.xml:4 Couldn't find frame parent: MainMenuBarArtFrame

**Comment by ynazar1** [comment]
Are you certain that it's from Arh? Because it seems like its coming from a different addon: https://addonswow.com/rwnarchdistance

**Comment by ynazar1** [comment]
Thanks for using Arh. It's better than that addon anyways ;)
