### ISSUE TITLE
10.2.6 Can't seem to get the addon to load?

### ISSUE THREAD

**Issue by nayab9** [ynazar1/Arh#13]
Not sure if its just me as I haven't seen an issue raised, but I cannot seem to get the addon to load since 10.2.6; WoW says its "out of date" and any attempt to reload seems to be stuck in a 'reload required' loop:

<img width="376" alt="image" src="https://github.com/ynazar1/Arh/assets/1916171/d3e8f4a5-81a8-478c-a1b5-977871917f9e">

**Comment by ynazar1** [comment]
Make sure you have Load out of Date addons checked...

![image](https://github.com/ynazar1/Arh/assets/43916837/f1ebfa27-fa3c-4f9d-bedf-b802cda16965)

**Comment by nayab9** [comment]
Thanks @ynazar1 !

I noticed the box was ticked, but when I clicked it to 'uncheck' it, nothing happened, then clicked it again and it unchecked, then I checked it off again to turn it on and its now loading!
For whatever reason, I think the GUI was showing a checkbox when it was not actually checked!

**Comment by ynazar1** [comment]
You can use wowup to get the latest version whenever i get un-lazy to update the toc. I'll usually fix issues if the addon doesn't work but TOC bumps are low priority ;) .
