### ISSUE TITLE
HUD not appearing for some users

### ISSUE THREAD

**Issue by Walayimuna** [ynazar1/Arh#17]
I tried to share the addon with other people, for some the HUD does not show.

What can cause this issue?

**Comment by ynazar1** [comment]
They are trying to use it on classic, not beta. 
They are downloading the code not the release. 
They have the option default set that the HUD doesn't display outside of dig area.

**Comment by Walayimuna** [comment]
I am using it on classic after prepatch release, it is working.
I sent them to this page, they downloaded the same version I am using.
The person I tried to help while they shared me their discord window showed me their entire process of:
- Deleting the old .lua file on the WTF folder
- Downloading the file from this website, same file I am using
- Installing it on the correct interface folder in the game folder
- Launching the game and selecting Archaeology Helper to load
- showing me the screen, where the mini-bar with the green, yellow and red button show up, but when they click on them, nothing happens.
- And when they type /arh, nothing shows up, like if the addon was not loaded

So, I don't know what else is needed, and am more than willing to provide any information needed to try to get this fixed.

I showed this to several streamers, for example, NukeShow has it working, and SubtleFW did the same process and it did not work for him, he had the same issue my friend had, the mini-bar appears, but clicking it or typing /arh addgreen / yellow / red does nothing.

**Comment by Walayimuna** [comment]
Thank you for all the work you do, it is truly appreciate, please, let me know what other information I need to provide to get my friends help fixing this

**Comment by ynazar1** [comment]
They'll need to get [bugsack ](https://www.curseforge.com/wow/addons/bugsack) and see what the error is then while it's not loading. 

They also need to make sure to load out of date addons (if needed uncheck and check that box again).

**Comment by Walayimuna** [comment]
Thank you.

I'll ask them to do that.

**Comment by Walayimuna** [comment]
This is their current addon list:
LoseControl
DBM
Auctionator
Details!
Diminish
Doom Cooldown Pulse
ElvUI
Gathermate2 + Data
Minimal Archaeology
Minimap Button Bag
OmniCC
Plater
TomTom
WeakAuras

**Comment by ynazar1** [comment]
It's not obvious what may be messing them up but one note that i'll say is that Minimap Button Bag is pretty terrible addon. 

I've fought a lot with it and minimap buttons. HidingBar https://www.curseforge.com/wow/addons/hidingbar should be used instead.

**Comment by ynazar1** [comment]
I've downloaded all the addons on the above list for the CataBeta and I'm unable to replicate the issue. Arh shows up properly and works without any errors. 

![image](https://github.com/ynazar1/Arh/assets/43916837/fbfd04c1-3064-45c1-98c7-9ceda1a3f8dd)

**Comment by Walayimuna** [comment]
I think I figured out the problem.

My friends didn't have the Ace3 installed.

Neither did I, I think the addon finds it because of either ElvUI or ArkInventory, which have Ace3 inside their files

One of them downloaded Ace3 from curse and it worked, asking the other to try it to confirm

**Comment by SubtleFW** [comment]
These are the errors I'm getting:
1.
3x Arh/arh.lua:11: Cannot find a library instance of "LibDBIcon-1.0".
[string "=[C]"]: in function `error'
[string "@GatherMate2/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Arh/arh.lua"]:11: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibDBIcon-1.0"."

2.
9x [string "*arh.xml:17_OnLoad"]:1: attempt to index field 'colorButton' (a nil value)
[string "*arh.xml:17_OnLoad"]:1: in function <[string "*arh.xml:17_OnLoad"]:1>

Locals:
self = Arh_MainFrame_ButtonRed {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = 3
(*temporary) = Arh_MainFrame_ButtonRed {
 0 = <userdata>
}
(*temporary) = "attempt to index field 'colorButton' (a nil value)"

3.
3x Arh/embeds.xml:3 Error loading Arh/libs/LibStub/LibStub.lua

4.
3x Arh/embeds.xml:4 Couldn't open Arh/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.xml

5.
3x Arh/embeds.xml:5 Couldn't open Arh/libs/AceGUI-3.0-41/AceGUI-3.0.xml

6.
3x Arh/embeds.xml:6 Couldn't open Arh/libs/AceConfig-3.0-3/AceConfig-3.0.xml

7.
3x Arh/embeds.xml:7 Couldn't open Arh/libs/AceConsole-3.0-7/AceConsole-3.0.xml

8.
3x Arh/embeds.xml:9 Error loading Arh/libs/LibDataBroker-1.1-4/LibDataBroker-1.1.lua

9.
3x Arh/embeds.xml:10 Error loading Arh/libs/LibDBIcon-1.0-52/LibDBIcon-1.0.lua

10.
3x Arh/arh.xml:126 Frame Arh_MainFrame: Unknown function Arh_MainFrame_OnLoad in element OnLoad

11.
3x Arh/arh.xml:127 Frame Arh_MainFrame: Unknown function Arh_MainFrame_OnEvent in element OnEvent

12.
3x Arh/arh.xml:128 Frame Arh_MainFrame: Unknown function Arh_MainFrame_OnMouseDown in element OnMouseDown

13.
43x [string "*arh.xml:10_OnEnter"]:1: attempt to call global 'Arh_ShowTooltip' (a nil value)
[string "*arh.xml:10_OnEnter"]:1: in function <[string "*arh.xml:10_OnEnter"]:1>

Locals:
self = Arh_MainFrame_ButtonYellow {
 0 = <userdata>
}
motion = true
(*temporary) = nil
(*temporary) = Arh_MainFrame_ButtonYellow {
 0 = <userdata>
}
(*temporary) = "attempt to call global 'Arh_ShowTooltip' (a nil value)"

14.
46x [string "*arh.xml:11_OnLeave"]:1: attempt to call global 'Arh_HideTooltip' (a nil value)
[string "*arh.xml:11_OnLeave"]:1: in function <[string "*arh.xml:11_OnLeave"]:1>

Locals:
self = Arh_MainFrame_ButtonYellow {
 0 = <userdata>
}
motion = true
(*temporary) = nil
(*temporary) = Arh_MainFrame_ButtonYellow {
 0 = <userdata>
}
(*temporary) = "attempt to call global 'Arh_HideTooltip' (a nil value)"

15.
43x [string "*arh.xml:131_OnEnter"]:1: attempt to call global 'Arh_ShowTooltip' (a nil value)
[string "*arh.xml:131_OnEnter"]:1: in function <[string "*arh.xml:131_OnEnter"]:1>

Locals:
self = Arh_MainFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:422
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 ApplyBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
}
motion = true
(*temporary) = nil
(*temporary) = Arh_MainFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:422
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 ApplyBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
}
(*temporary) = "attempt to call global 'Arh_ShowTooltip' (a nil value)"

16.
42x [string "*arh.xml:132_OnLeave"]:1: attempt to call global 'Arh_HideTooltip' (a nil value)
[string "*arh.xml:132_OnLeave"]:1: in function <[string "*arh.xml:132_OnLeave"]:1>

Locals:
self = Arh_MainFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:422
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 ApplyBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
}
motion = true
(*temporary) = nil
(*temporary) = Arh_MainFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:422
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 ApplyBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
}
(*temporary) = "attempt to call global 'Arh_HideTooltip' (a nil value)"

**Comment by ynazar1** [comment]
Get the release zip from releases section. Not the source one. The source doesn't package libraries needed. You needs this zip https://github.com/ynazar1/Arh/releases/download/2.0.7-126/Arh-2.0.7-126.zip which is currently latest release with libraries.

**Comment by ynazar1** [comment]
@SubtleFW  You're having the same issue as https://github.com/ynazar1/Arh/issues/9

**Comment by Pocokk** [comment]
3x Arh/arh.lua:1148: Usage: local continentID, worldPosition = C_Map.GetWorldPosFromMapPos(uiMapID, mapPosition)
[string "=[C]"]: in function `GetWorldPosFromMapPos'
[string "@Arh/arh.lua"]:1148: in function `GetPos'
[string "@Arh/arh.lua"]:1189: in function `GetPosYards'
[string "@Arh/arh.lua"]:1772: in function `Arh_HudFrame_OnUpdate'
[string "@Arh/arh.lua"]:1864: in function <Arh/arh.lua:1860>
[string "=[C]"]: in function `Show'
[string "@Arh/arh.lua"]:99: in function <Arh/arh.lua:97>
[string "@Arh/arh.lua"]:175: in function `ToggleHUD'
[string "@Arh/arh.lua"]:1588: in function `Arh_MainFrame_Init'
[string "@Arh/arh.lua"]:1479: in function <Arh/arh.lua:1469>
[string "@Arh/arh.lua"]:1488: in function <Arh/arh.lua:1486>

Locals:
(*temporary) = 189
(*temporary) = nil


getting this lua error as well for some reason.

**Comment by ynazar1** [comment]
Closing this. Re-open if it's still an issue vs what I suspect a user error.
