### ISSUE TITLE
Can't move/reposition the Main Window

### ISSUE THREAD

**Issue by Pocokk** [ynazar1/Arh#18]
The "Locked" option is not selected, but still can't move the Survey and the three colored dots around, its annoying to have it in the center of the screen.

What should I do?

**Comment by Pocokk** [comment]
Turns out you have to drag it above the colored dots precisely to move the window around.

**Comment by ynazar1** [comment]
There's actually a small invisible rectangle around the UI that I never bothered to figure out how to make visible again after texture calls changed few expansions ago. Glad you figured it out.
