### ISSUE TITLE
GetWorldPosFromMapPos Error

### ISSUE THREAD

**Issue by ynazar1** [ynazar1/Arh#19]
```
3x Arh/arh.lua:1148: Usage: local continentID, worldPosition = C_Map.GetWorldPosFromMapPos(uiMapID, mapPosition)
[string "=[C]"]: in function `GetWorldPosFromMapPos'
[string "@Arh/arh.lua"]:1148: in function `GetPos'
[string "@Arh/arh.lua"]:1189: in function `GetPosYards'
[string "@Arh/arh.lua"]:1772: in function `Arh_HudFrame_OnUpdate'
[string "@Arh/arh.lua"]:1864: in function <Arh/arh.lua:1860>
[string "=[C]"]: in function `Show'
[string "@Arh/arh.lua"]:99: in function <Arh/arh.lua:97>
[string "@Arh/arh.lua"]:175: in function `ToggleHUD'
[string "@Arh/arh.lua"]:1588: in function `Arh_MainFrame_Init'
[string "@Arh/arh.lua"]:1479: in function <Arh/arh.lua:1469>
[string "@Arh/arh.lua"]:1488: in function <Arh/arh.lua:1486>

Locals:
(*temporary) = 189
(*temporary) = nil
```

getting this lua error as well for some reason.

_Originally posted by @Pocokk in https://github.com/ynazar1/Arh/issues/17#issuecomment-2105139966_

**Comment by ynazar1** [comment]
@Pocokk 
what addon release are you on? 
at what point in time this error appears?
Does it happen when you do `/reload`?
Where is your character located at when this happens?

**Comment by Pocokk** [comment]
Latest release available from here
it happened while I was inside a raid instance (ICC)
it went away after a while, not sure if I did a /reload or just finished the raid and left it altogether, but now I'm outdoor and farming the proff without any issue

**Comment by ynazar1** [comment]
Iirc that call isn't available in instances. Or was it in raids? Either way I thought there was built in protection against it running. I'll  try to replicate issue by going to instance, though no promises. 

I'll appreciate if you can catch exact set of conditions when it happens. So I can replicate it for testing possible workarounds.

**Comment by Pocokk** [comment]
All I remember is that I was inside ICC, just installed the addon, did a /reload and when I tried to left mouse-click on the mini-map icon, that error occurred.

**Comment by ynazar1** [comment]
Thanks for the report. I found the bug and it was exactly as i was expecting. Since a lot of calls don't work in instances. Trying to decide if i want to work around it or simply disable addon while in instance.

**Comment by Pocokk** [comment]
Another thing, I've found the mini-map icon left-click option (show/hide the main windows) doesn't work at all, even if I'm near/at a digsite (yet doesn't getting any lua error upon spam clicking it, so its weird).

**Comment by ynazar1** [comment]
The in-instance nonensese is actually a bug in retail too :( . I feeling semi-lazy about it since i *strongly* recommend setting auto-toggle and never worrying about stuff popping up in instance again. 

The minimap icon is correct behavior when you have it selected to auto-hide show. 
![image](https://github.com/ynazar1/Arh/assets/43916837/1daef582-6795-4b6e-9c7e-e0c42901f02b)

**Comment by Pocokk** [comment]
Ah didn't know about that, sorry!

Yep, from now on its auto-toggle, but not everyone is aware of it and might cause issues to them in the future.

To prevent future bugreports, any chance to "block" the window in instance environment later perhaps?

**Comment by ynazar1** [comment]
I've made auto-toggle the default years ago. Which perhaps makes it slightly confusing for first time users as HUD doesn't show up when addon is loaded

**Comment by Pocokk** [comment]
That's a relief, alright then.

**Comment by ynazar1** [comment]
Grab the latest https://github.com/ynazar1/Arh/blob/main/Arh.lua file, replace yours in addons directory and test please. 

I've added back the rectangle frame and the addon errors in ICC/raid should be gone now. I think. It just doesn't quite operate in instances but the frame at least loads. Not that it ever operated in instances.

**Comment by Pocokk** [comment]
Yeah, looks good so far, thank you!

**Comment by ynazar1** [comment]
New release has the fix.
