### ISSUE TITLE
Feature request: Hide Main Window while HUD still enabled

### ISSUE THREAD

**Issue by maexey** [ynazar1/Arh#20]
thanks. love this Addon,

The Main Window (Color-Buttons, Arrow, Shovel) are sometimes in the way. E.g., when you are standing right on top of a discovered relic. I have the Color-Buttons mapped to keys.
As a workaround I have set Alpha and Scaling for the Main Window to min. But there is still a small area that reacts to right click. And I may accidently hide the HUD or open the options window while right clicking close to the middle.

**Comment by maexey** [comment]
just noticed the main window can also be moved out of the way, DOH

**Comment by ynazar1** [comment]
I brought back the rectangle around the buttons so it's more obvious
