### ISSUE TITLE
Cata: LUA error on login

### ISSUE THREAD

**Issue by maexey** [ynazar1/Arh#23]
Version 2.0.8-1100-bugfix, all other addons disabled except BugSack/BugGrabber

1x Arh/arh.lua:1612: attempt to call field 'GetSpellInfo' (a nil value)
[string "@Arh/arh.lua"]:1612: in function `Arh_MainFrame_Init'
[string "@Arh/arh.lua"]:1494: in function <Arh/arh.lua:1484>
[string "@Arh/arh.lua"]:1503: in function <Arh/arh.lua:1501>

Locals:
PaneBackdrop = <table> {
 bgFile = "Interface\ChatFrame\ChatFrameBackground"
 tileSize = 16
 edgeFile = "Interface\Tooltips\UI-Tooltip-Border"
 tile = true
 edgeSize = 16
 insets = <table> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = Arh_MainFrame_ButtonDig {
 0 = <userdata>
 Canceled = false
 TooltipText = "|cffffff78Left Click|r: cast Survey
|cffffff78Right Click|r: Show/Hide the HUD
|cffffff78Middle Click|r: Open archaeology window"
 CanceledTexture = Texture {
 }
}
(*temporary) = "spell"
(*temporary) = nil
(*temporary) = 80451
(*temporary) = "attempt to call field 'GetSpellInfo' (a nil value)"
Config = <table> {
 RegisterOptionsTable = <function> defined @Arh/libs/AceConfig-3.0/AceConfig-3.0.lua:45
}
OptionsTable = <table> {
 args = <table> {
 }
 type = "group"
}
LDB = <table> {
 attributestorage = <table> {
 }
 pairs = <function> defined @Arh/libs/LibDataBroker-1.1/LibDataBroker-1.1.lua:70
 NewDataObject = <function> defined @Arh/libs/LibDataBroker-1.1/LibDataBroker-1.1.lua:36
 callbacks = <table> {
 }
 ipairs = <function> defined @Arh/libs/LibDataBroker-1.1/LibDataBroker-1.1.lua:81
 RegisterCallback = <function> defined @Arh/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 GetNameByDataObject = <function> defined @Arh/libs/LibDataBroker-1.1/LibDataBroker-1.1.lua:63
 GetDataObjectByName = <function> defined @Arh/libs/LibDataBroker-1.1/LibDataBroker-1.1.lua:59
 UnregisterCallback = <function> defined @Arh/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 domt = <table> {
 }
 proxystorage = <table> {
 }
 DataObjectIterator = <function> defined @Arh/libs/LibDataBroker-1.1/LibDataBroker-1.1.lua:55
 namestorage = <table> {
 }
 UnregisterAllCallbacks = <function> defined @Arh/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
}
LDBo = <table> {
}
addonName = "Arh"
addon = <table> {
 hiddenFrame = ArhHiddenFrame {
 }
 ConsCache = <table> {
 }
 mount = <function> defined @Arh/arh.lua:1366
 ResetSettings = <function> defined @Arh/arh.lua:318
 UpdateConsSizes = <function> defined @Arh/arh.lua:1086
 CheckSuppress = <function> defined @Arh/arh.lua:186
 ToggleHUD = <function> defined @Arh/arh.lua:167
 vars = <table> {
 }
 HUD_config_update = <function> defined @Arh/arh.lua:1711
 SaveDifs = <function> defined @Arh/arh.lua:1337
 GetPos = <function> defined @Arh/arh.lua:1146
 UpdateCons = <function> defined @Arh/arh.lua:1140
 init_travelform = <function> defined @Arh/arh.lua:1371
 GetDigsiteTracking = <function> defined @Arh/arh.lua:343
 GetPosYards = <function> defined @Arh/arh.lua:1200
 OnGathering = <function> defined @Arh/arh.lua:1357
 UpdateAlphaEverything = <function> defined @Arh/arh.lua:1127
 HookArchy = <function> defined @Arh/arh.lua:132
 UpdateAlpha = <function> defined @Arh/arh.lua:1116
 colorButton = <table> {
 }
 ReturnAllToCache = <function> defined @Arh/arh.lua:1041
 Config = <function> defined @Arh/arh.lua:212
 UpdateConsPositions = <function> defined @Arh/arh.lua:1097
 ToggleArch = <function> defined @Arh/arh.lua:220
 ReturnLastToCache = <function> defined @Arh/arh.lua:1046
 ToggleMainFrame = <function> defined @Arh/arh.lua:152
 ConsArray = <table> {
 }
 SetDigsiteTracking = <function> defined @Arh/arh.lua:357
}
cs = <function> defined @Arh/arh.lua:232
L = <table> {
}
minimapIcon = <table> {
 Register = <function> defined @Arh/libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:381
 callbacks = <table> {
 }
 Unlock = <function> defined @Arh/libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:398
 IsButtonInCompart

**Comment by maexey** [comment]
also getting this on my Druid:

4x Arh/arh.lua:1393: attempt to call field 'GetSpellInfo' (a nil value)
[string "@Arh/arh.lua"]:1393: in function `init_travelform'
[string "@Arh/arh.lua"]:1508: in function <Arh/arh.lua:1501>

Locals:
self = <table> {
 hiddenFrame = ArhHiddenFrame {
 }
 ConsCache = <table> {
 }
 mount = <function> defined @Arh/arh.lua:1366
 ResetSettings = <function> defined @Arh/arh.lua:318
 UpdateConsSizes = <function> defined @Arh/arh.lua:1086
 CheckSuppress = <function> defined @Arh/arh.lua:186
 ToggleHUD = <function> defined @Arh/arh.lua:167
 vars = <table> {
 }
 HUD_config_update = <function> defined @Arh/arh.lua:1711
 suppress = true
 SaveDifs = <function> defined @Arh/arh.lua:1337
 GetPos = <function> defined @Arh/arh.lua:1146
 UpdateCons = <function> defined @Arh/arh.lua:1140
 init_travelform = <function> defined @Arh/arh.lua:1371
 GetDigsiteTracking = <function> defined @Arh/arh.lua:343
 GetPosYards = <function> defined @Arh/arh.lua:1200
 OnGathering = <function> defined @Arh/arh.lua:1357
 UpdateAlphaEverything = <function> defined @Arh/arh.lua:1127
 HookArchy = <function> defined @Arh/arh.lua:132
 UpdateAlpha = <function> defined @Arh/arh.lua:1116
 colorButton = <table> {
 }
 ReturnAllToCache = <function> defined @Arh/arh.lua:1041
 Config = <function> defined @Arh/arh.lua:212
 UpdateConsPositions = <function> defined @Arh/arh.lua:1097
 ToggleArch = <function> defined @Arh/arh.lua:220
 ReturnLastToCache = <function> defined @Arh/arh.lua:1046
 ToggleMainFrame = <function> defined @Arh/arh.lua:152
 ConsArray = <table> {
 }
 SetDigsiteTracking = <function> defined @Arh/arh.lua:357
}
mt = nil
spellid = 40120
spellid_travelForm = 783
spellid_flyingForm = 33950
spellid_swiftFlyingForm = 40120
(*temporary) = <function> defined =[C]:-1
(*temporary) = "/cast [nostance:3,nocombat] %s"
(*temporary) = nil
(*temporary) = 40120
(*temporary) = "attempt to call field 'GetSpellInfo' (a nil value)"
addon = <table> {
 hiddenFrame = ArhHiddenFrame {
 }
 ConsCache = <table> {
 }
 mount = <function> defined @Arh/arh.lua:1366
 ResetSettings = <function> defined @Arh/arh.lua:318
 UpdateConsSizes = <function> defined @Arh/arh.lua:1086
 CheckSuppress = <function> defined @Arh/arh.lua:186
 ToggleHUD = <function> defined @Arh/arh.lua:167
 vars = <table> {
 }
 HUD_config_update = <function> defined @Arh/arh.lua:1711
 suppress = true
 SaveDifs = <function> defined @Arh/arh.lua:1337
 GetPos = <function> defined @Arh/arh.lua:1146
 UpdateCons = <function> defined @Arh/arh.lua:1140
 init_travelform = <function> defined @Arh/arh.lua:1371
 GetDigsiteTracking = <function> defined @Arh/arh.lua:343
 GetPosYards = <function> defined @Arh/arh.lua:1200
 OnGathering = <function> defined @Arh/arh.lua:1357
 UpdateAlphaEverything = <function> defined @Arh/arh.lua:1127
 HookArchy = <function> defined @Arh/arh.lua:132
 UpdateAlpha = <function> defined @Arh/arh.lua:1116
 colorButton = <table> {
 }
 ReturnAllToCache = <function> defined @Arh/arh.lua:1041
 Config = <function> defined @Arh/arh.lua:212
 UpdateConsPositions = <function> defined @Arh/arh.lua:1097
 ToggleArch = <function> defined @Arh/arh.lua:220
 ReturnLastToCache = <function> defined @Arh/arh.lua:1046
 ToggleMainFrame = <function> defined @Arh/arh.lua:152
 ConsArray = <table> {
 }
 SetDigsiteTracking = <function> defined @Arh/arh.lua:357
}
cfg = <table> {
 MainFrame = <table> {
 }
 HUD = <table> {
 }
 DigSites = <table> {
 }
 Minimap = <table> {
 }
}
id2cname = <table> {
 1 = "Green"
 2 = "Yellow"
 3 = "Red"
}

**Comment by ynazar1** [comment]
Thanks! Traveling right now. Will take a look in a day or two. Use v207 temporarily for cata. I may just flag it for cata only and not for retail while api catches up. The api divergence was really frustrating. 

Sent from my mobile headquarters.  
 
  On Tue, Aug 6, 2024 at 5:23 PM, ***@***.***> wrote:   



also getting this on my Druid:

4x Arh/arh.lua:1393: attempt to call field 'GetSpellInfo' (a nil value)
[string ***@***.***/arh.lua"]:1393: in function `init_travelform'
[string ***@***.***/arh.lua"]:1508: in function <Arh/arh.lua:1501>

Locals:
self = 
 {
hiddenFrame = ArhHiddenFrame {
}
ConsCache = 

 {
}
mount = defined @Arh/arh.lua:1366
ResetSettings = defined @Arh/arh.lua:318
UpdateConsSizes = defined @Arh/arh.lua:1086
CheckSuppress = defined @Arh/arh.lua:186
ToggleHUD = defined @Arh/arh.lua:167
vars = 

 {
}
HUD_config_update = defined @Arh/arh.lua:1711
suppress = true
SaveDifs = defined @Arh/arh.lua:1337
GetPos = defined @Arh/arh.lua:1146
UpdateCons = defined @Arh/arh.lua:1140
init_travelform = defined @Arh/arh.lua:1371
GetDigsiteTracking = defined @Arh/arh.lua:343
GetPosYards = defined @Arh/arh.lua:1200
OnGathering = defined @Arh/arh.lua:1357
UpdateAlphaEverything = defined @Arh/arh.lua:1127
HookArchy = defined @Arh/arh.lua:132
UpdateAlpha = defined @Arh/arh.lua:1116
colorButton = 

 {
}
ReturnAllToCache = defined @Arh/arh.lua:1041
Config = defined @Arh/arh.lua:212
UpdateConsPositions = defined @Arh/arh.lua:1097
ToggleArch = defined @Arh/arh.lua:220
ReturnLastToCache = defined @Arh/arh.lua:1046
ToggleMainFrame = defined @Arh/arh.lua:152
ConsArray = 

 {
}
SetDigsiteTracking = defined @Arh/arh.lua:357
}
mt = nil
spellid = 40120
spellid_travelForm = 783
spellid_flyingForm = 33950
spellid_swiftFlyingForm = 40120
(*temporary) = defined =[C]:-1
(*temporary) = "/cast [nostance:3,nocombat] %s"
(*temporary) = nil
(*temporary) = 40120
(*temporary) = "attempt to call field 'GetSpellInfo' (a nil value)"
addon = 

 {
hiddenFrame = ArhHiddenFrame {
}
ConsCache = 

 {
}
mount = defined @Arh/arh.lua:1366
ResetSettings = defined @Arh/arh.lua:318
UpdateConsSizes = defined @Arh/arh.lua:1086
CheckSuppress = defined @Arh/arh.lua:186
ToggleHUD = defined @Arh/arh.lua:167
vars = 

 {
}
HUD_config_update = defined @Arh/arh.lua:1711
suppress = true
SaveDifs = defined @Arh/arh.lua:1337
GetPos = defined @Arh/arh.lua:1146
UpdateCons = defined @Arh/arh.lua:1140
init_travelform = defined @Arh/arh.lua:1371
GetDigsiteTracking = defined @Arh/arh.lua:343
GetPosYards = defined @Arh/arh.lua:1200
OnGathering = defined @Arh/arh.lua:1357
UpdateAlphaEverything = defined @Arh/arh.lua:1127
HookArchy = defined @Arh/arh.lua:132
UpdateAlpha = defined @Arh/arh.lua:1116
colorButton = 

 {
}
ReturnAllToCache = defined @Arh/arh.lua:1041
Config = defined @Arh/arh.lua:212
UpdateConsPositions = defined @Arh/arh.lua:1097
ToggleArch = defined @Arh/arh.lua:220
ReturnLastToCache = defined @Arh/arh.lua:1046
ToggleMainFrame = defined @Arh/arh.lua:152
ConsArray = 

 {
}
SetDigsiteTracking = defined @Arh/arh.lua:357
}
cfg = 

 {
MainFrame = 

 {
}
HUD = 

 {
}
DigSites = 

 {
}
Minimap = 

 {
}
}
id2cname = 

 {
1 = "Green"
2 = "Yellow"
3 = "Red"
}

**Comment by ynazar1** [comment]
Since the cata API didn't seem to have changed during retail prepatch. I've rolled back cata version on curseforge to use the [2.0.7 version ](https://github.com/ynazar1/Arh/releases/tag/2.0.7-127) which uses pre 11.0.0 API.

**Comment by ynazar1** [comment]
The new cata version should be using 4.4.1 and 11.0.5 API. I've updated the version on curse some time ago (toc is likely a little out of date) but api should work. 

Can you please confirm that everything works as it should on latest Arh? Thanks in advance.
