### ISSUE TITLE
Nodes on HUD not rotating

### ISSUE THREAD

**Issue by nelsonj1998** [ynazar1/Arh#6]
For years, the nodes on my HUD rotated as I turned my character, but they no longer do. If I enable the 'Rotate Minimap' option in the WoW UI Minimap options, the nodes on the HUD will rotate correctly but I prefer not to play with that enabled for the minimap. It's a bit inconvenient to enable the minimap rotation option each time I get to a digsite just to get the HUD to rotate while I'm digging.

**Comment by ynazar1** [comment]
Apparently variable name changed in [dc9543580d03986098d3bf337748d34f1c3e44ea](https://github.com/Nevcairiel/GatherMate2/blob/dc9543580d03986098d3bf337748d34f1c3e44ea/Display.lua)
Breaking that functionality... Well fixed!
