### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by phobos927** [ynazar1/Arh#9]
https://photo-screen.ru/i/4d2jDm1vG 
Not draggable.
Does not work.
"arh" command does not work.

**Comment by ynazar1** [comment]
Make sure you're using the latest version from [Releases section](https://github.com/ynazar1/Arh/releases) 
Here are how my options are set: 
![image](https://github.com/ynazar1/Arh/assets/43916837/ac877f8c-c50e-4811-9f9d-ba23e9ec80cb)

Uncheck 'locked' to make it draggable... 'Toggle with digsite' will turn it on and off automatically but disables manual toggle. 

if you're still having issues... let me know if there are any error messages that are being caught by bugsack and whether or not just having this addon alone (with gathermate) works for you or not... and we'll go from there.

**Comment by phobos927** [comment]
Sorry. I'm dumb. Everything works, I downloaded the master branch, not the release.

**Comment by ynazar1** [comment]
Ah yes, the build script pulls in required libraries to function. Glad this is resolved.
